version: '3'

services:
  messengerclient:
    container_name: "messagerouter_messengerclient"
    build:
      context: ./messengerclient
      dockerfile: ./Dockerfile
    volumes:
    - ./messengerclient/config:/home/node/app/config
    env_file:
    - ./messengerclient/config/config.env
